-- MySQL Script generated by MySQL Workbench
-- Fri Aug  2 01:36:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema koa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `koa` ;

-- -----------------------------------------------------
-- Table `koa`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `name` VARCHAR(255) NULL DEFAULT NULL COMMENT '그룹명',
  `image_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '이미지 URL',
  `creator` INT(11) NULL DEFAULT NULL COMMENT '그룹 생성자',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `koa`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `email` VARCHAR(255) NULL DEFAULT NULL COMMENT '이메일',
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT '비밀번호',
  `animal_id` VARCHAR(15) NULL DEFAULT NULL COMMENT '반려견 식별번호',
  `name` VARCHAR(70) NULL DEFAULT NULL COMMENT '이름',
  `nickname` VARCHAR(70) NULL DEFAULT NULL COMMENT '닉네임',
  `carrier` TINYINT(4) NULL DEFAULT NULL COMMENT '통신사',
  `telephone` INT(13) NULL DEFAULT NULL COMMENT '전화번호',
  `image_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '이미지URL',
  `introduce` TEXT NULL DEFAULT NULL COMMENT '자기소개',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '수정일자',
  `is_deleted` TINYINT(4) NULL DEFAULT '0' COMMENT '탈퇴여부',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '회원';


-- -----------------------------------------------------
-- Table `koa`.`feeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`feeds` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `member_id` INT(11) NULL DEFAULT NULL COMMENT '멤버아이디',
  `group_id` INT(11) NULL DEFAULT NULL COMMENT '그룹 아이디',
  `type` TINYINT(4) NULL DEFAULT NULL COMMENT '피드 유형',
  `content` TEXT NULL DEFAULT NULL COMMENT '내용',
  `image_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '이미지URL',
  `total_like` INT(11) NULL DEFAULT NULL COMMENT '총 좋아요 수',
  `total_comment` INT(11) NULL DEFAULT NULL COMMENT '총 코멘트 수',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (`id`),
  INDEX `member__idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_groups_feeds_1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_feeds_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `koa`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_members_feeds_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `koa`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '피드';


-- -----------------------------------------------------
-- Table `koa`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `feed_id` INT(11) NULL DEFAULT NULL COMMENT '피드 아이디',
  `p_id` INT(11) NULL DEFAULT NULL COMMENT '부모 아이디',
  `comment` TEXT NULL DEFAULT NULL COMMENT '코멘트',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (`id`),
  INDEX `fk_feed_comments_1_idx` (`feed_id` ASC) VISIBLE,
  CONSTRAINT `fk_feed_comments_1`
    FOREIGN KEY (`feed_id`)
    REFERENCES `koa`.`feeds` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '코멘트';


-- -----------------------------------------------------
-- Table `koa`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `hashtag` TEXT NULL DEFAULT NULL COMMENT '해시태그',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '태그';


-- -----------------------------------------------------
-- Table `koa`.`feed_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`feed_tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `feed_id` INT(11) NULL DEFAULT NULL COMMENT '피드 아이디',
  `tag_id` INT(11) NULL DEFAULT NULL COMMENT '태그 아이디',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  PRIMARY KEY (`id`),
  INDEX `fk_feeds_feed_tags_1_idx` (`feed_id` ASC) VISIBLE,
  INDEX `fk_tags_feed_tags_1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_feeds_feed_tags_1`
    FOREIGN KEY (`feed_id`)
    REFERENCES `koa`.`feeds` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tags_feed_tags_1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `koa`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '피드 태그';


-- -----------------------------------------------------
-- Table `koa`.`group_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`group_members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `member_id` INT(11) NULL DEFAULT NULL,
  `group_id` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_members_group_members_1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_groups_group_members_1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_group_members_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `koa`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_members_group_members_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `koa`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '그룹 멤버';


-- -----------------------------------------------------
-- Table `koa`.`group_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koa`.`group_tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이디',
  `group_id` INT(11) NULL DEFAULT NULL COMMENT '그룹 아이디',
  `tag_id` INT(11) NULL DEFAULT NULL COMMENT '태그 아이디',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  PRIMARY KEY (`id`),
  INDEX `fk_groups_group_tags_1_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_tags_group_tags_1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_group_tags_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `koa`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tags_group_tags_1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `koa`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '그룹 태그';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;